version: '3.7'
services:
  ssh-server:
    image: docker_sshd:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "4000:22"
      
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    # networks:
    #   - webnet